steps:

  - name: 'gcr.io/cloud-builders/docker'
    entrypoint: "sh"
    args: [ '-c', 'docker pull gcr.io/ucdlib-pubreg/jena-fuseki-eb:latest || true' ]
    env: 
      - 'REPO_NAME=$REPO_NAME'
      - 'BRANCH_NAME=$BRANCH_NAME'
      - 'SHORT_SHA=$SHORT_SHA'
      - 'TAG_NAME=$TAG_NAME'

  - name: 'gcr.io/cloud-builders/docker'
    entrypoint: "sh"
    args: [ '-c', 'docker build --cache-from gcr.io/ucdlib-pubreg/jena-fuseki-eb:latest -t gcr.io/ucdlib-pubreg/jena-fuseki-eb:$TAG_NAME .' ]

  - name: 'gcr.io/cloud-builders/docker'
    entrypoint: "sh"
    args: [ '-c', 'docker tag gcr.io/ucdlib-pubreg/jena-fuseki-eb:$TAG_NAME gcr.io/ucdlib-pubreg/jena-fuseki-eb:latest' ]

images: ['gcr.io/ucdlib-pubreg/jena-fuseki-eb:latest', 'gcr.io/ucdlib-pubreg/jena-fuseki-eb:$TAG_NAME']

timeout: 2400s